import type { Retorno } from "./types";

export const initialRetornos: Retorno[] = [
  {
    id: "ret-001",
    type: "roi_return",
    propertyId: "prop-001",
    propertyTitle: "Apartamento en San Isidro – Lote 12B",
    userId: "user-001",
    userName: "Carlos Mendoza Ríos",
    userEmail: "carlos.mendoza@gmail.com",
    amount: 8500,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "bank_transfer",
    bankName: "BCP",
    accountHolder: "Carlos Mendoza Ríos",
    accountNumber: "19012345678901",
    transferReference: "TRF-20260610-0023",
    createdAt: "2026-06-10T10:00:00",
    confirmedAt: "2026-06-10T10:05:00",
    createdBy: "Valentina Ríos",
  },
  {
    id: "ret-002",
    type: "refund",
    propertyId: "prop-002",
    propertyTitle: "Local Comercial Miraflores – Av. Larco",
    userId: "user-002",
    userName: "Ana Lucía Torres",
    userEmail: "ana.torres@outlook.com",
    amount: 3200,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "card",
    cardLastFour: "4521",
    cardholderName: "ANA L TORRES",
    createdAt: "2026-06-08T14:30:00",
    confirmedAt: "2026-06-08T14:35:00",
    createdBy: "Luis Ramírez",
    ticket: {
      id: "tkt-001",
      retornoId: "ret-002",
      status: "flagged",
      title: "El monto recibido no coincide con lo esperado",
      reason: "wrong_amount",
      description:
        "<p>El retorno recibido fue de S/ 3,200 pero según mi cálculo debería haber sido S/ 3,800 considerando el porcentaje de mi inversión inicial de S/ 19,000 y el ROI acordado del 20%.</p>",
      attachments: [],
      createdAt: "2026-06-09T09:15:00",
      activity: [
        {
          id: "act-001",
          type: "created",
          title: "Ticket creado",
          byUser: "Ana Lucía Torres",
          byRole: "client",
          createdAt: "2026-06-09T09:15:00",
        },
        {
          id: "act-002",
          type: "flagged",
          title: "Ticket marcado como observado",
          byUser: "Sistema",
          byRole: "admin",
          createdAt: "2026-06-09T09:15:01",
        },
      ],
    },
  },
  {
    id: "ret-003",
    type: "goal_not_reached",
    propertyId: "prop-003",
    propertyTitle: "Casa en Surco – Urbanización Las Casuarinas",
    userId: "user-003",
    userName: "Roberto Sánchez Vega",
    userEmail: "rsanchez@empresa.pe",
    amount: 12000,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "bank_transfer",
    bankName: "Interbank",
    accountHolder: "Roberto Sánchez Vega",
    accountNumber: "2001234567890",
    transferReference: "TRF-20260605-0041",
    createdAt: "2026-06-05T09:00:00",
    confirmedAt: "2026-06-05T09:10:00",
    createdBy: "Valentina Ríos",
    ticket: {
      id: "tkt-002",
      retornoId: "ret-003",
      status: "in_review",
      title: "No reconozco la devolución como correcta",
      reason: "wrong_property",
      description:
        "<p>Esta devolución corresponde a una propiedad en Surco pero yo solo tengo inversiones en San Isidro y Miraflores. Por favor verificar.</p>",
      attachments: [],
      createdAt: "2026-06-06T11:00:00",
      assignedToId: "admin-002",
      assignedToName: "Luis Ramírez",
      assignedAt: "2026-06-06T12:00:00",
      activity: [
        {
          id: "act-003",
          type: "created",
          title: "Ticket creado",
          byUser: "Roberto Sánchez Vega",
          byRole: "client",
          createdAt: "2026-06-06T11:00:00",
        },
        {
          id: "act-004",
          type: "flagged",
          title: "Ticket marcado como observado",
          byUser: "Sistema",
          byRole: "admin",
          createdAt: "2026-06-06T11:00:01",
        },
        {
          id: "act-005",
          type: "assigned",
          title: "Ticket asignado a Luis Ramírez",
          byUser: "Valentina Ríos",
          byRole: "admin",
          createdAt: "2026-06-06T12:00:00",
        },
        {
          id: "act-006",
          type: "in_review",
          title: "Ticket en revisión",
          byUser: "Luis Ramírez",
          byRole: "admin",
          createdAt: "2026-06-06T12:00:01",
        },
      ],
    },
  },
  {
    id: "ret-004",
    type: "roi_return",
    propertyId: "prop-004",
    propertyTitle: "Departamento en Barranco – Av. San Martín",
    userId: "user-004",
    userName: "Patricia Huamán Quispe",
    userEmail: "phuaman@yahoo.com",
    amount: 5600,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "card",
    cardLastFour: "8823",
    cardholderName: "PATRICIA HUAMAN",
    createdAt: "2026-06-01T15:00:00",
    confirmedAt: "2026-06-01T15:05:00",
    createdBy: "Valentina Ríos",
    ticket: {
      id: "tkt-003",
      retornoId: "ret-004",
      status: "resolved",
      title: "Consulta sobre retención de impuestos aplicada",
      reason: "other",
      description:
        "<p>Quisiera saber por qué se aplicó una retención en este retorno. No tenía conocimiento de ello.</p>",
      attachments: [],
      createdAt: "2026-06-02T08:00:00",
      assignedToId: "admin-001",
      assignedToName: "Valentina Ríos",
      assignedAt: "2026-06-02T09:00:00",
      resolvedAt: "2026-06-02T11:00:00",
      resolvedByName: "Valentina Ríos",
      activity: [
        {
          id: "act-007",
          type: "created",
          title: "Ticket creado",
          byUser: "Patricia Huamán Quispe",
          byRole: "client",
          createdAt: "2026-06-02T08:00:00",
        },
        {
          id: "act-008",
          type: "flagged",
          title: "Ticket marcado como observado",
          byUser: "Sistema",
          byRole: "admin",
          createdAt: "2026-06-02T08:00:01",
        },
        {
          id: "act-009",
          type: "assigned",
          title: "Ticket asignado a Valentina Ríos",
          byUser: "Valentina Ríos",
          byRole: "admin",
          createdAt: "2026-06-02T09:00:00",
        },
        {
          id: "act-010",
          type: "in_review",
          title: "Ticket en revisión",
          byUser: "Valentina Ríos",
          byRole: "admin",
          createdAt: "2026-06-02T09:00:01",
        },
        {
          id: "act-011",
          type: "admin_message",
          title: "Respuesta del equipo",
          description:
            "<p>Estimada Patricia, la retención del 5% aplicada corresponde a la normativa SBS vigente sobre ganancias de capital en remates judiciales. Este porcentaje se descuenta antes del retorno neto. Puede revisar el detalle en su estado de cuenta. Quedamos disponibles para cualquier duda adicional.</p>",
          byUser: "Valentina Ríos",
          byRole: "admin",
          createdAt: "2026-06-02T11:00:00",
        },
        {
          id: "act-012",
          type: "resolved",
          title: "Ticket resuelto",
          byUser: "Valentina Ríos",
          byRole: "admin",
          createdAt: "2026-06-02T11:00:01",
        },
      ],
    },
  },
  {
    id: "ret-005",
    type: "roi_return",
    propertyId: "prop-005",
    propertyTitle: "Oficina en San Borja – Edificio Torre Norte",
    userId: "user-001",
    userName: "Carlos Mendoza Ríos",
    userEmail: "carlos.mendoza@gmail.com",
    amount: 4200,
    currency: "USD",
    status: "confirmed",
    paymentMethod: "bank_transfer",
    bankName: "BBVA",
    accountHolder: "Carlos Mendoza Ríos",
    accountNumber: "0011234567890111",
    transferReference: "TRF-20260520-0018",
    createdAt: "2026-05-20T12:00:00",
    confirmedAt: "2026-05-20T12:15:00",
    createdBy: "Luis Ramírez",
  },
];
