import type { Retorno } from "./types";

export const initialRetornos: Retorno[] = [
  // ── standard-demo (Carlos Mendoza) ───────────────────────────────────────
  {
    id: "ret-001",
    type: "roi_return",
    propertyId: "prop-001",
    propertyTitle: "Apartamento en San Isidro – Lote 12B",
    userId: "standard-demo",
    userName: "Carlos Mendoza",
    userEmail: "standard@remata.com",
    amount: 8500,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "bank_transfer",
    bankName: "BCP",
    accountHolder: "Carlos Mendoza",
    accountNumber: "19012345678901",
    transferReference: "TRF-20260610-0023",
    createdAt: "2026-06-10T10:00:00",
    confirmedAt: "2026-06-10T10:05:00",
    createdBy: "Admin Operaciones",
  },
  {
    id: "ret-002",
    type: "refund",
    propertyId: "prop-002",
    propertyTitle: "Local Comercial Miraflores – Av. Larco",
    userId: "standard-demo",
    userName: "Carlos Mendoza",
    userEmail: "standard@remata.com",
    amount: 3200,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "card",
    cardLastFour: "4521",
    cardholderName: "CARLOS MENDOZA",
    createdAt: "2026-06-08T14:30:00",
    confirmedAt: "2026-06-08T14:35:00",
    createdBy: "Admin Operaciones",
    ticket: {
      id: "tkt-001",
      retornoId: "ret-002",
      status: "flagged",
      title: "El monto recibido no coincide con lo esperado",
      reason: "wrong_amount",
      description:
        "<p>El retorno recibido fue de S/ 3,200 pero según mi cálculo debería haber sido S/ 3,800 considerando el porcentaje de mi inversión inicial de S/ 19,000 y el ROI acordado del 20%.</p>",
      attachments: [],
      createdAt: "2026-06-09T09:15:00",
      activity: [
        {
          id: "act-001",
          type: "created",
          title: "Ticket creado",
          byUser: "Carlos Mendoza",
          byRole: "client",
          createdAt: "2026-06-09T09:15:00",
        },
        {
          id: "act-002",
          type: "flagged",
          title: "Ticket marcado como observado",
          byUser: "Sistema",
          byRole: "admin",
          createdAt: "2026-06-09T09:15:01",
        },
      ],
    },
  },
  {
    id: "ret-003",
    type: "goal_not_reached",
    propertyId: "prop-003",
    propertyTitle: "Casa en Surco – Urbanización Las Casuarinas",
    userId: "standard-demo",
    userName: "Carlos Mendoza",
    userEmail: "standard@remata.com",
    amount: 12000,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "bank_transfer",
    bankName: "Interbank",
    accountHolder: "Carlos Mendoza",
    accountNumber: "2001234567890",
    transferReference: "TRF-20260605-0041",
    createdAt: "2026-06-05T09:00:00",
    confirmedAt: "2026-06-05T09:10:00",
    createdBy: "Admin Operaciones",
    ticket: {
      id: "tkt-002",
      retornoId: "ret-003",
      status: "in_review",
      title: "No reconozco esta devolución como correcta",
      reason: "wrong_property",
      description:
        "<p>Esta devolución aparece relacionada a una propiedad en Surco, pero no tengo ninguna inversión activa en esa propiedad. Por favor verificar.</p>",
      attachments: [],
      createdAt: "2026-06-06T11:00:00",
      assignedToId: "acc-admin",
      assignedToName: "Admin Operaciones",
      assignedAt: "2026-06-06T12:00:00",
      activity: [
        {
          id: "act-003",
          type: "created",
          title: "Ticket creado",
          byUser: "Carlos Mendoza",
          byRole: "client",
          createdAt: "2026-06-06T11:00:00",
        },
        {
          id: "act-004",
          type: "flagged",
          title: "Ticket marcado como observado",
          byUser: "Sistema",
          byRole: "admin",
          createdAt: "2026-06-06T11:00:01",
        },
        {
          id: "act-005",
          type: "assigned",
          title: "Ticket asignado a Admin Operaciones",
          byUser: "Super Admin",
          byRole: "admin",
          createdAt: "2026-06-06T12:00:00",
        },
        {
          id: "act-006",
          type: "in_review",
          title: "Ticket en revisión",
          byUser: "Admin Operaciones",
          byRole: "admin",
          createdAt: "2026-06-06T12:00:01",
        },
      ],
    },
  },
  {
    id: "ret-004",
    type: "roi_return",
    propertyId: "prop-004",
    propertyTitle: "Departamento en Barranco – Av. San Martín",
    userId: "standard-demo",
    userName: "Carlos Mendoza",
    userEmail: "standard@remata.com",
    amount: 5600,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "card",
    cardLastFour: "8823",
    cardholderName: "CARLOS MENDOZA",
    createdAt: "2026-06-01T15:00:00",
    confirmedAt: "2026-06-01T15:05:00",
    createdBy: "Admin Operaciones",
    ticket: {
      id: "tkt-003",
      retornoId: "ret-004",
      status: "resolved",
      title: "Consulta sobre retención de impuestos aplicada",
      reason: "other",
      description:
        "<p>Quisiera saber por qué se aplicó una retención en este retorno. No tenía conocimiento de ello.</p>",
      attachments: [],
      createdAt: "2026-06-02T08:00:00",
      assignedToId: "acc-superadmin",
      assignedToName: "Super Admin",
      assignedAt: "2026-06-02T09:00:00",
      resolvedAt: "2026-06-02T11:00:00",
      resolvedByName: "Super Admin",
      activity: [
        {
          id: "act-007",
          type: "created",
          title: "Ticket creado",
          byUser: "Carlos Mendoza",
          byRole: "client",
          createdAt: "2026-06-02T08:00:00",
        },
        {
          id: "act-008",
          type: "flagged",
          title: "Ticket marcado como observado",
          byUser: "Sistema",
          byRole: "admin",
          createdAt: "2026-06-02T08:00:01",
        },
        {
          id: "act-009",
          type: "assigned",
          title: "Ticket asignado a Super Admin",
          byUser: "Super Admin",
          byRole: "admin",
          createdAt: "2026-06-02T09:00:00",
        },
        {
          id: "act-010",
          type: "in_review",
          title: "Ticket en revisión",
          byUser: "Super Admin",
          byRole: "admin",
          createdAt: "2026-06-02T09:00:01",
        },
        {
          id: "act-011",
          type: "admin_message",
          title: "Respuesta oficial del equipo",
          description:
            "<p>Estimado Carlos, la retención del 5% aplicada corresponde a la normativa SBS vigente sobre ganancias de capital en remates judiciales. Este porcentaje se descuenta automáticamente antes del retorno neto. Puede solicitar el certificado de retenciones escribiéndonos por este medio. Quedamos a su disposición.</p>",
          byUser: "Super Admin",
          byRole: "admin",
          createdAt: "2026-06-02T11:00:00",
        },
        {
          id: "act-012",
          type: "resolved",
          title: "Ticket resuelto",
          byUser: "Super Admin",
          byRole: "admin",
          createdAt: "2026-06-02T11:00:01",
        },
      ],
    },
  },
  {
    id: "ret-005",
    type: "roi_return",
    propertyId: "prop-005",
    propertyTitle: "Oficina en San Borja – Edificio Torre Norte",
    userId: "standard-demo",
    userName: "Carlos Mendoza",
    userEmail: "standard@remata.com",
    amount: 4200,
    currency: "USD",
    status: "confirmed",
    paymentMethod: "bank_transfer",
    bankName: "BBVA",
    accountHolder: "Carlos Mendoza",
    accountNumber: "0011234567890111",
    transferReference: "TRF-20260520-0018",
    createdAt: "2026-05-20T12:00:00",
    confirmedAt: "2026-05-20T12:15:00",
    createdBy: "Admin Operaciones",
  },

  // ── premium-demo (Valentina Ríos) ────────────────────────────────────────
  {
    id: "ret-006",
    type: "roi_return",
    propertyId: "prop-006",
    propertyTitle: "Penthouse Vista al Mar – Chorrillos",
    userId: "premium-demo",
    userName: "Valentina Ríos",
    userEmail: "premium@remata.com",
    amount: 48000,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "bank_transfer",
    bankName: "BCP",
    accountHolder: "Valentina Ríos",
    accountNumber: "19098765432109",
    transferReference: "TRF-20260612-0055",
    createdAt: "2026-06-12T09:00:00",
    confirmedAt: "2026-06-12T09:10:00",
    createdBy: "Super Admin",
  },
  {
    id: "ret-007",
    type: "roi_return",
    propertyId: "prop-007",
    propertyTitle: "Edificio Residencial Miraflores – Torre B",
    userId: "premium-demo",
    userName: "Valentina Ríos",
    userEmail: "premium@remata.com",
    amount: 32500,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "card",
    cardLastFour: "9912",
    cardholderName: "VALENTINA RIOS",
    createdAt: "2026-06-03T11:00:00",
    confirmedAt: "2026-06-03T11:05:00",
    createdBy: "Super Admin",
    ticket: {
      id: "tkt-004",
      retornoId: "ret-007",
      status: "flagged",
      title: "El retorno no refleja el ROI premium acordado",
      reason: "wrong_amount",
      description:
        "<p>Según mi contrato premium, el ROI acordado era del 18% sobre S/ 210,000. El retorno debería ser S/ 37,800 y no S/ 32,500. Por favor revisar el cálculo.</p>",
      attachments: [],
      createdAt: "2026-06-04T10:00:00",
      activity: [
        {
          id: "act-013",
          type: "created",
          title: "Ticket creado",
          byUser: "Valentina Ríos",
          byRole: "client",
          createdAt: "2026-06-04T10:00:00",
        },
        {
          id: "act-014",
          type: "flagged",
          title: "Ticket marcado como observado",
          byUser: "Sistema",
          byRole: "admin",
          createdAt: "2026-06-04T10:00:01",
        },
      ],
    },
  },
  {
    id: "ret-008",
    type: "refund",
    propertyId: "prop-008",
    propertyTitle: "Casa de Playa – Asia, Cañete",
    userId: "premium-demo",
    userName: "Valentina Ríos",
    userEmail: "premium@remata.com",
    amount: 95000,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "bank_transfer",
    bankName: "Scotiabank",
    accountHolder: "Valentina Ríos",
    accountNumber: "3301234567891",
    transferReference: "TRF-20260528-0032",
    createdAt: "2026-05-28T08:00:00",
    confirmedAt: "2026-05-28T08:20:00",
    createdBy: "Super Admin",
    ticket: {
      id: "tkt-005",
      retornoId: "ret-008",
      status: "resolved",
      title: "No reconozco el número de cuenta destino",
      reason: "processing_error",
      description:
        "<p>El comprobante de transferencia muestra una cuenta con terminación 7891 pero mi cuenta registrada termina en 7981. Por favor confirmar si el fondos llegaron correctamente.</p>",
      attachments: [],
      createdAt: "2026-05-29T09:00:00",
      assignedToId: "acc-superadmin",
      assignedToName: "Super Admin",
      assignedAt: "2026-05-29T10:00:00",
      resolvedAt: "2026-05-29T14:00:00",
      resolvedByName: "Super Admin",
      activity: [
        {
          id: "act-015",
          type: "created",
          title: "Ticket creado",
          byUser: "Valentina Ríos",
          byRole: "client",
          createdAt: "2026-05-29T09:00:00",
        },
        {
          id: "act-016",
          type: "flagged",
          title: "Ticket marcado como observado",
          byUser: "Sistema",
          byRole: "admin",
          createdAt: "2026-05-29T09:00:01",
        },
        {
          id: "act-017",
          type: "assigned",
          title: "Ticket asignado a Super Admin",
          byUser: "Super Admin",
          byRole: "admin",
          createdAt: "2026-05-29T10:00:00",
        },
        {
          id: "act-018",
          type: "in_review",
          title: "Ticket en revisión",
          byUser: "Super Admin",
          byRole: "admin",
          createdAt: "2026-05-29T10:00:01",
        },
        {
          id: "act-019",
          type: "admin_message",
          title: "Respuesta oficial del equipo",
          description:
            "<p>Estimada Valentina, hemos verificado la transferencia. El número de cuenta es correcto — termina en 7891 tal como figura en su ficha de datos actualizada el 15 de mayo. El dígito que menciona (7981) corresponde a una cuenta anterior que fue cerrada. Los fondos han sido acreditados exitosamente. Si necesita el voucher de confirmación del banco, háganoslo saber.</p>",
          byUser: "Super Admin",
          byRole: "admin",
          createdAt: "2026-05-29T14:00:00",
        },
        {
          id: "act-020",
          type: "resolved",
          title: "Ticket resuelto",
          byUser: "Super Admin",
          byRole: "admin",
          createdAt: "2026-05-29T14:00:01",
        },
      ],
    },
  },
  {
    id: "ret-009",
    type: "goal_not_reached",
    propertyId: "prop-009",
    propertyTitle: "Lote Comercial San Juan de Lurigancho – Sector 4",
    userId: "premium-demo",
    userName: "Valentina Ríos",
    userEmail: "premium@remata.com",
    amount: 21000,
    currency: "PEN",
    status: "confirmed",
    paymentMethod: "bank_transfer",
    bankName: "Interbank",
    accountHolder: "Valentina Ríos",
    accountNumber: "2009876543210",
    transferReference: "TRF-20260515-0011",
    createdAt: "2026-05-15T13:00:00",
    confirmedAt: "2026-05-15T13:15:00",
    createdBy: "Admin Operaciones",
  },
  {
    id: "ret-010",
    type: "roi_return",
    propertyId: "prop-010",
    propertyTitle: "Oficina Ejecutiva La Molina – Piso 8",
    userId: "premium-demo",
    userName: "Valentina Ríos",
    userEmail: "premium@remata.com",
    amount: 18750,
    currency: "USD",
    status: "confirmed",
    paymentMethod: "card",
    cardLastFour: "3301",
    cardholderName: "VALENTINA RIOS",
    createdAt: "2026-05-05T10:30:00",
    confirmedAt: "2026-05-05T10:35:00",
    createdBy: "Super Admin",
  },
];
